# Generated by Django 5.2.6 on 2025-09-30 11:06

from django.db import migrations
from django.contrib.auth.models import Group


def create_default_groups(apps, schema_editor):
    """Create default groups for the application"""
    groups_data = [
        {'name': 'Tenant Owners', 'description': 'Full access to tenant management and all features'},
        {'name': 'Project Managers', 'description': 'Manage projects, teams, and client relationships'},
        {'name': 'Employees', 'description': 'Standard employee access to assigned projects'},
        {'name': 'Clients', 'description': 'Limited access to view project progress and invoices'},
        {'name': 'Administrators', 'description': 'System-wide administrative access'},
    ]

    for group_data in groups_data:
        Group.objects.get_or_create(
            name=group_data['name'],
            defaults={'name': group_data['name']}
        )


def remove_default_groups(apps, schema_editor):
    """Remove default groups (for migration reversal)"""
    Group.objects.filter(name__in=[
        'Tenant Owners', 'Project Managers', 'Employees', 'Clients', 'Administrators'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_company_size_tenant_industry_tenant_phone_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_groups, remove_default_groups),
    ]
