# Generated by Django 5.2.6 on 2025-10-14 17:15

from django.db import migrations


def populate_tenant_created_by(apps, schema_editor):
    """Populate created_by field for existing tenants with their first owner"""
    Tenant = apps.get_model('accounts', 'Tenant')
    UserTenant = apps.get_model('accounts', 'UserTenant')

    updated_count = 0
    for tenant in Tenant.objects.all():
        # Find the first UserTenant with is_owner=True for this tenant
        # Order by id to get the first created (assuming sequential IDs)
        first_owner = UserTenant.objects.filter(
            tenant=tenant,
            is_owner=True
        ).order_by('id').first()

        if first_owner:
            tenant.created_by = first_owner.user
            tenant.save()
            updated_count += 1
            print(f"Set created_by for tenant '{tenant.name}' to user '{first_owner.user.email}'")
        else:
            print(f"No owner found for tenant '{tenant.name}' - created_by remains None")

    print(f"Updated {updated_count} tenants with created_by information")


def reverse_populate_tenant_created_by(apps, schema_editor):
    """Reverse migration - clear created_by field"""
    Tenant = apps.get_model('accounts', 'Tenant')
    updated_count = Tenant.objects.filter(created_by__isnull=False).update(created_by=None)
    print(f"Cleared created_by for {updated_count} tenants")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_tenant_created_by'),
    ]

    operations = [
        migrations.RunPython(
            populate_tenant_created_by,
            reverse_populate_tenant_created_by
        ),
    ]
