services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env.staging
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.staging
    environment:
      - DJANGO_ENV=staging
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - RUN_SETUP=false
    command: gunicorn saasCRM.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_staging:/app/static
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  frontend:
    
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_URL=${SITE_URL}/api
      - CI=true
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  postgres_staging_data:
  static_staging:
