services:
  backend:
    image: ghcr.io/calvin-okumu/carlhub-erp/backend:latest
    restart: always
     environment:
       - DJANGO_ENV=staging
       - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
       - SECRET_KEY=${SECRET_KEY}
       - RUN_SETUP=false
    command: gunicorn saasCRM.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_staging:/app/static
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/calvin-okumu/carlhub-erp/frontend:latest
    restart: always
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_URL=http://staging.local:8000/api
    ports:
      - "80:3000"

volumes:
  static_staging:
