
services:
  backend:
    image: your-dockerhub-username/saascrm-backend:latest
    restart: always
    environment:
      - DJANGO_ENV=production
      - DATABASE_URL=postgresql://saascrm_user:saascrm_password@db:5432/saascrm_db
      - SECRET_KEY=super-secret-prod-key
      - RUN_SETUP=false
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_prod:/app/static
    ports:
      - "8000:8000"

  frontend:
    image: your-dockerhub-username/saascrm-frontend:latest
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.yourdomain.com
    command: npm run start
    ports:
      - "80:3000"

volumes:
  static_prod:
