
services:
  backend:
    image: your-dockerhub-username/saascrm-backend:latest
    restart: always
    environment:
      - DJANGO_ENV=staging
      - DATABASE_URL=postgresql://saascrm_user:saascrm_password@db:5432/saascrm_db
      - SECRET_KEY=staging-secret-key
      - RUN_SETUP=false
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_staging:/app/static
    ports:
      - "8000:8000"

  frontend:
    image: your-dockerhub-username/saascrm-frontend:latest
    restart: always
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_API_URL=https://staging.yourdomain.com/api
    command: npm run start
    ports:
      - "80:3000"

volumes:
  static_staging:
