# Generated by Django 5.2.6 on 2025-10-08 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_invoice_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect')], db_index=True, default='prospect', max_length=10),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('testing', 'Testing'), ('done', 'Done')], db_index=True, default='to_do', max_length=12),
        ),
    ]
