# Generated by Django 5.2.6 on 2025-09-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_milestone_progress'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Tenant',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='organization',
            new_name='tenant',
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestone',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='project.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='project.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='project.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project.tenant'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
