# Generated by Django 5.2.6 on 2025-09-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20250928_0941'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenant',
            table='project_tenant',
        ),
    ]
