# Generated by Django 5.2.6 on 2025-09-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_customuser_email_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenant',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
