# Generated by Django 5.2.6 on 2025-09-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_usertenant_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenant',
            name='role',
            field=models.CharField(default='Employee', max_length=100),
        ),
    ]
