# Generated by Django 5.2.6 on 2025-09-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_usertenant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
