
name: Smart CI/CD Pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main, dev]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ci-test-secret-key-not-for-production-use
      DEBUG: true
      ALLOWED_HOSTS: localhost,127.0.0.1,testserver
      SITE_URL: http://127.0.0.1:8000
      MULTI_TENANCY_ENABLED: false
      DB_NAME: test_saascrm_db
      DB_USER: saascrm_user
      DB_PASSWORD: saascrm_password
      DB_HOST: localhost
      DB_PORT: 5432
      DATABASE_URL: postgresql://saascrm_user:saascrm_password@localhost:5432/test_saascrm_db
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
           restore-keys: |
             ${{ runner.os }}-pip-

       - name: Install dependencies
         run: |
           cd backend
           python -m pip install --upgrade pip
            pip install -r requirements.txt

       - name: Create environment file
         run: |
           cd backend
           echo "SECRET_KEY=${{ env.SECRET_KEY }}" > .env
           echo "DEBUG=${{ env.DEBUG }}" >> .env
           echo "ALLOWED_HOSTS=${{ env.ALLOWED_HOSTS }}" >> .env
           echo "SITE_URL=${{ env.SITE_URL }}" >> .env
           echo "MULTI_TENANCY_ENABLED=${{ env.MULTI_TENANCY_ENABLED }}" >> .env
           echo "DB_NAME=${{ env.DB_NAME }}" >> .env
           echo "DB_USER=${{ env.DB_USER }}" >> .env
           echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env
           echo "DB_HOST=${{ env.DB_HOST }}" >> .env
           echo "DB_PORT=${{ env.DB_PORT }}" >> .env
            echo "DATABASE_URL=${{ env.DATABASE_URL }}" >> .env

       - name: Run unit tests
         run: |
           cd backend
           python manage.py test --tag=unit --verbosity=2

  detect-changes:
    name: Detect Code Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed areas
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
              - 'requirements.txt'
              - 'Dockerfile.backend'
              - '.github/workflows/ci.yml'
            frontend:
              - 'frontend/**'
              - 'package.json'
              - 'package-lock.json'
              - '.github/workflows/ci.yml'

  backend:
    name: Backend Tests & Build
    needs: [unit-tests, detect-changes]
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ci-test-secret-key-not-for-production-use
      DEBUG: true
      ALLOWED_HOSTS: localhost,127.0.0.1,testserver
      SITE_URL: http://127.0.0.1:8000
      MULTI_TENANCY_ENABLED: false
      DB_NAME: test_saascrm_db
      DB_USER: saascrm_user
      DB_PASSWORD: saascrm_password
      DB_HOST: localhost
      DB_PORT: 5432
      DATABASE_URL: postgresql://saascrm_user:saascrm_password@localhost:5432/test_saascrm_db

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create environment file
        run: |
          cd backend
          echo "SECRET_KEY=${{ env.SECRET_KEY }}" > .env
          echo "DEBUG=${{ env.DEBUG }}" >> .env
          echo "ALLOWED_HOSTS=${{ env.ALLOWED_HOSTS }}" >> .env
          echo "SITE_URL=${{ env.SITE_URL }}" >> .env
          echo "MULTI_TENANCY_ENABLED=${{ env.MULTI_TENANCY_ENABLED }}" >> .env
          echo "DB_NAME=${{ env.DB_NAME }}" >> .env
          echo "DB_USER=${{ env.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ env.DB_HOST }}" >> .env
          echo "DB_PORT=${{ env.DB_PORT }}" >> .env
          echo "DJANGO_ENV=${{ env.DJANGO_ENV }}" >> .env

      - name: Build Backend Image (Dev)
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          tags: carlhub-erp/backend:dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend Image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/calvin-okumu/carlhub-erp/backend:latest
            ghcr.io/calvin-okumu/carlhub-erp/backend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/calvin-okumu/carlhub-erp/backend:latest
          cache-to: type=inline

  frontend:
    name: Frontend Tests & Build
    needs: [unit-tests, detect-changes]
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run frontend setup
        run: |
          cd frontend
          node scripts/setup.js --ci

      - name: Run lint
        run: |
          cd frontend
          npm run lint

      - name: Run type checking
        run: |
          cd frontend
          npx tsc --noEmit

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Run security audit
        run: |
          cd frontend
          npm audit --audit-level=moderate || echo "Audit warnings found, continuing..."

      - name: Build Frontend Image (Dev)
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          tags: carlhub-erp/frontend:dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build & Push Frontend Image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/calvin-okumu/carlhub-erp/frontend:latest
            ghcr.io/calvin-okumu/carlhub-erp/frontend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/calvin-okumu/carlhub-erp/frontend:latest
          cache-to: type=inline

  create-tag:
    name: Create Git Tag for Release
    needs: [backend, frontend]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to push tags

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="release-$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::7}"
          echo "Creating tag $TAG"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG
          git push origin $TAG

